---
# tasks file for install_openscap
- name: install packages
  yum:
    name:
      - firewalld
      - httpd
      - openscap-scanner
      - scap-security-guide
      - python3-lxml
  become: true
  become_method: sudo

- name: 
  firewalld:
    service: http
    permanent: yes
    zone: public
    state: enabled
  become: true
  become_method: sudo

- name: reload firewalld
  systemd:
    state: reloaded
    enabled: yes
    name: firewalld
  become: true
  become_method: sudo

- name: enable httpd
  systemd:
    state: started
    enabled: yes
    name: httpd
  become: true
  become_method: sudo

