---
# tasks file for install_openscap
- name: install packages
  yum:
    name:
      - httpd
      - openscap-scanner
      - scap-security-guide
      - python3-lxml
  become: true
  become_method: sudo

- name: enable httpd
  systemd:
    state: started
    enabled: yes
    name: httpd

#- name: run openscap scan
#  command: oscap xccdf eval \
#    --fetch-remote-resources 
    #--profile xccdf_org.ssgproject.content_profile_ospp \ --results-arf /tmp/arf.xml \
#    --report /var/www/html/report.html \
#    /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml
#  become: yes
#  register: scan_result
#  failed_when: scan_result.rc == 1
  
- name: read score
  xml:
    path: /tmp/arf.xml
    xpath: /arf:asset-report-collection
    content: attribute
  register: score

- debug:
    msg: "{{ score }}"
