---
# tasks file for install_openscap
- name: install packages
  yum:
    name:
      - httpd
      - openscap-scanner
      - scap-security-guide
  become: true
  become_method: sudo

- name: enable httpd
  systemd:
    state: started
    enabled: yes
    name: httpd