---
# tasks file for install_openscap
- name: install packages
  yum:
    name:
      - firewalld
      - httpd
      - openscap-scanner
      - scap-security-guide
      - python3-lxml
  become: true
  become_method: sudo

- name: 
  firewalld:
    service: http
    permanent: yes
    zone: public
    state: enabled
  become: true
  become_method: sudo

- name: reload firewalld
  systemd:
    state: reloaded
    enabled: yes
    name: firewalld
  become: true
  become_method: sudo

- name: enable httpd
  systemd:
    state: started
    enabled: yes
    name: httpd
  become: true
  become_method: sudo

- name: run openscap scan
  command: oscap xccdf eval \
    --fetch-remote-resources 
    --profile xccdf_org.ssgproject.content_profile_ospp \ --results-arf /tmp/arf.xml \
    --report /var/www/html/report.html \
    /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml
  become: yes
  register: scan_result
  failed_when: scan_result.rc == 1
  
- name: grep arf.xml
  command: /usr/bin/egrep '<score' /tmp/arf.xml
  register: grep_output

- name: get score
  set_fact:
    scan_score: "{{ grep_output.stdout | regex_replace('^.*?<score.*?>(.*)<.*$', '\\1') }}"

- debug:
    msg: "{{ scan_score }}"

- debug:
    msg: "need mitigation"
  when: scan_score | float <= scan_threshold | float

- name: set_mitigation
  set_fact:
    mitigate: true
  when: scan_score | float <= scan_threshold | float

- name: SERVICENOW IF CHANGED
  block:
    - name: CREATE AN INCIDENT
      snow_record:
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        instance: "{{ snow_instance }}"
        state: present
        table: incident
        data:
          short_description: "CONFIG OUT OF COMPLIANCE ON {{inventory_hostname}}"
          severity: 3
          priority: 2
          caller_id: "System Administrator"
          comments: "The configuration:\n--------\n ospp compliance\n--------\n is below 85% on {{inventory_hostname}}"
      register: snow_var
      delegate_to: localhost

    - name: DEBUG SNOW_VAR
      debug:
        var: snow_var.record.number
  when: mitigate|bool
